version: '3'

services:
  app:
    container_name: app
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

    networks:
      - dbappnet

  db:
    container_name: db
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    #ports:
    #  - "3306:3306"
    volumes:
      #- "./db/sql-scripts:/docker-entrypoint-initdb.d"
      - "dbdata:/var/lib/mysql"
    networks:
      - dbappnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3

  nginx:
    container_name: nginx
    image: nginx:alpine-slim
    ports:
    - 80:80

    volumes:
      #- "./proxy/conf:/etc/nginx/conf.d"
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf 
      - "./app/static:/usr/share/nginx/html/static"
    depends_on:
      - app
    networks:
      - dbappnet

volumes:
  dbdata:

networks:
  dbappnet:
