version: '3'
services:
  # app:
  #   container_name: app
  #   build: ./app
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  db:
    container_name: db
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - "./db/sql-scripts:/docker-entrypoint-initdb.d"
      - "dbdata:/var/lib/mysql"
volumes:
  dbdata: