apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqlstate
spec:
  replicas: 2
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: jack3131/mysql:0.1.2
        name: db
        ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
        envFrom:
        - secretRef:
            name: mysecret
        volumeMounts:
        - name: mypd
          mountPath: /var/lib/mysql    
      
  volumeClaimTemplates:
  - metadata:
      name: mypd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi