apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
  name: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    team: electify

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db
        team: electify
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "testdb"


