
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
      - port: 3306
        targetPort: 3306
---

apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: electify
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008
  type: NodePort


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db
        team: electify
    spec:
      containers:
      - image: mysql:8.0
        name: db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "testdb"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: electify
  name: electify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electify

  template:
    metadata:
      labels:
        app: electify
        team: electify
    spec:
      containers:
      - image: jack3131/electify:latest
        name: app
        command: ["/bin/sh", "-c", "python app.py"]
