name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Start Docker Compose
      run: docker compose up -d

    - name: Run Tests

      run: |
        sleep 5
        docker ps -a
        bash ./app/e2e.sh