name: CI/CD

on:
  push:
    branches:
      - master
      - feature/**

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

    # checkout
    - name: Checkout Repository
      uses: actions/checkout@v3
    

    # docker compose up
    - name: Start Docker Compose
      run: docker compose up -d

    # end to end testing
    - name: Run Tests
      run: bash ./app/e2e.sh

    # git tag
    - name: tagger
      if: github.ref == 'refs/heads/master'
      id: tagger
      env:          
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |

        tag=$(bash ./app/tagger.sh)
        export TAG=$tag
        echo "::set-env name=TAG::$TAG"

    # login to dockerhub    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # publish to dockerhub    
    - name: publish to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: |
        docker images
        docker tag portfolio-app:latest jack3131/electify:$TAG
        docker push jack3131/electify:$TAG

        docker tag portfolio-db:latest jack3131/mysql:$TAG
        docker push jack3131/mysql:$TAG

    # push tags
    - name: push tags
      if: github.ref == 'refs/heads/master'
      run: |
        git push origin $TAG


    # Deploy (trig argo)
    - name: Deploy
      run: |
        mkdir lab && cd lab
        git clone https://jack3131:Lab654654@gitlab.com/foo105/portfolio.git
        cd portfolio/electify/templates
        TTAG="jack3131\/mysql:$TAG"
        sed -i "s/jack3131\/mysql:[0-9]\+\.[0-9]\+\.[0-9]\+/$TTAG/g" statefullset-db.yaml
        sed -i "s/jack3131\/electify:[0-9]\+\.[0-9]\+\.[0-9]\+/$TTAG/g" app-deploy.yaml

        cat statefullset-db.yaml | grep -i jack
        cat app-deploy.yaml | grep -i jack

        git config --global user.email "you@example.com"
        git config --global user.name "Github Action"
        git commit -am "$TAG"
        git push https://jack3131:Lab654654@gitlab.com/foo105/portfolio.git master

    # report
    - name: failure
      if: failure()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        message="<b>❌ CI for branch:</b> $GITHUB_REF_NAME failed 🚨💀
         <b>Tag:</b> $TAG
         <b>Link:</b> <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Link</a>
         <b>Run number:</b> $GITHUB_RUN_NUMBER"

        curl -s --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=$message" --data "parse_mode=HTML" "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null


    - name: success
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        message="<b>✅ CI for branch:</b> $GITHUB_REF_NAME succeeded 🚀🤘
         <b>Tag:</b> $TAG
         <b>Link:</b> <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Link</a>
         <b>Run number:</b> $GITHUB_RUN_NUMBER"

        curl -s --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=$message" --data "parse_mode=HTML" "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null


