name: CI/CD

on:
  push:
    branches:
      - master
      - feature/**

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

    # checkout
    - name: Checkout Repository
      uses: actions/checkout@v3
    

    # docker compose up
    - name: Start Docker Compose
      run: docker compose up -d

    # end to end testing
    - name: Run Tests
      run: bash ./app/e2e.sh

    # git tag
    - name: tagger
      if: github.ref == 'refs/heads/master'
      id: tag
      # env:          
      #   ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |

        tag=$(bash ./app/tagger.sh)
        echo "TAG=$tag" >> $GITHUB_OUTPUT
        # export TAG=$tag
        # echo "::set-env name=TAG::$TAG"

    # login to dockerhub    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # publish to dockerhub    
    - name: publish to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: |
        docker tag portfolio-app:latest jack3131/electify:${{ steps.tag.outputs.TAG }}
        docker push jack3131/electify:${{ steps.tag.outputs.TAG }}

        docker tag portfolio-db:latest jack3131/mysql:${{ steps.tag.outputs.TAG }}
        docker push jack3131/mysql:${{ steps.tag.outputs.TAG }}

    # push tags
    - name: push tags
      if: github.ref == 'refs/heads/master'
      run: |
        git push origin ${{ steps.tag.outputs.TAG }}


    - name: Github login
      if: github.ref == 'refs/heads/master'
      uses: actions/checkout@v3
      with: 
        repository: Jo-Bm/PortfolioGOC
        ref: master
        token: ${{ secrets.GHTOKEN }}
    
    - name: Deploy (trig argo)
      run: |

        
        TTAG="jack3131\/mysql:${{ steps.tag.outputs.TAG }}"
        sed -i "s/jack3131\/mysql:[0-9]\+\.[0-9]\+\.[0-9]\+/$TTAG/g" electify/templates/statefullset-db.yaml
        TTAG="jack3131\/electify:${{ steps.tag.outputs.TAG }}"
        sed -i "s/jack3131\/electify:[0-9]\+\.[0-9]\+\.[0-9]\+/$TTAG/g" electify/templates/app-deploy.yaml

        git config --global user.email "you@example.com"
        git config --global user.name "Github Action"
        git commit -am "${{ steps.tag.outputs.TAG }}"

        git push origin master


    # report
    - name: failure
      if: failure()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        message="<b>❌ CI for branch:</b> $GITHUB_REF_NAME failed 🚨💀
         <b>Tag:</b> ${{ steps.tag.outputs.TAG }}
         <b>Link:</b> <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Link</a>
         <b>Run number:</b> $GITHUB_RUN_NUMBER"

        curl -s --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=$message" --data "parse_mode=HTML" "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null


    - name: success
      if: success()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        message="<b>✅ CI for branch:</b> $GITHUB_REF_NAME succeeded 🚀🤘
         <b>Tag:</b> ${{ steps.tag.outputs.TAG }}
         <b>Link:</b> <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Link</a>
         <b>Run number:</b> $GITHUB_RUN_NUMBER"

        curl -s --data-urlencode "chat_id=$TELEGRAM_CHAT_ID" --data-urlencode "text=$message" --data "parse_mode=HTML" "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" > /dev/null


